using ClosedXML.Excel;
using Fitness_Tracking.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Fitness_Tracking.Controllers
{
    [Authorize]
    [ApiController]
    [Route("api/version")]
    public class VersionController : ControllerBase, IVersionedService
    {
        [HttpGet]
        [MapToApiVersion("1.0")]
        [Obsolete("This version is obsolete.")]
        public int GetVersion1()
        {
            int version1Value = 10;
            return (version1Value);
        }

        [HttpGet]
        [MapToApiVersion("2.0")]
        public string GetVersion2()
        {
            string version2Value = "Text from version 2.0";
            return version2Value;
        }

        [HttpGet]
        [MapToApiVersion("3.0")]
        public IActionResult GetVersion3()
        {
            using (var workbook = new XLWorkbook())
            {
                var worksheet = workbook.Worksheets.Add("Sheet1");
                worksheet.Cell("A1").Value = "Hello, world!";
                worksheet.Cell("A2").Value = "This is an Excel file generated by the server.";

                using (var stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    var content = stream.ToArray();
                    return File(content, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "file.xlsx");
                }
            }
        }
    }
}